# This is a basic workflow to help you get started with Actions

name: Build and Deploy Logic App. 

env:
  LA_NAME: 'lastandarddevdemoapp'
  LA_RG: 'la-standard-dev-demo'
  

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  logic_app_build: 
    name: Build 
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout
      uses: actions/checkout@v1
    - name: Package logic
      run: (mkdir -p ./output; zip -r ./output/logic.zip .)
    - name: Upload app zip package
      uses: actions/upload-artifact@v2
      with:
        name: logic
        path: ./output/
        retention-days: 1
        
  logic_app_deploy: 
      name: Deploy 
      runs-on: ubuntu-latest
      needs: [logic_app_build]
      environment: 
        name: Dev
      steps: 
      - name: Checkout
        uses: actions/checkout@v1    
      
      - name: Login via Az module
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
          enable-AzPSSession: true 
      - uses: actions/download-artifact@master
        with:
          name: logic
          path: ./output/

      - name: Get publish Profile
        id: publishprofile
        uses: azure/powershell@v1
        with:
          inlineScript: |
            $profile = Get-AzWebAppPublishingProfile `
                -ResourceGroupName ${{ env.LA_RG }} `
                -Name ${{ env.LA_NAME }}
            $profile = $profile.Replace("`r", "").Replace("`n", "")
            Write-Output "::set-output name=profile::$profile"
          azPSVersion: latest        
          
      - name: Deploy to Azure Logic App
        uses: Azure/functions-action@v1.3.1
        id: la
        with:
          app-name: ${{ env.LA_RG }}
          package: './output/logic.zip'
          publish-profile: ${{steps.publishprofile.outputs.profile}}

      - name: Update appsettings
        id: appsettings
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az logicapp config appsettings set --name ${{ env.LA_NAME }} --resource-group ${{ env.LA_RG }} --settings "serviceBus_connectionString=${{ secrets.SB_CONN }} azureTables_connectionString=${{ secrets.STOR_CONN }}"
      
      - name: Swap parameter files 
        id: params
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az logicapp deploy --resource-group ${{ env.LA_RG }} --name ${{ env.LA_NAME }} --src-path  logic/azure.parameters.json --type static --target-path parameters.json
